### ISSUE TITLE
package-untar-buffer: Package does not untar cleanly into directory ocodo-svg-modelines-0.1.0/

### ISSUE THREAD

**Issue by maacl** [ocodo/ocodo-svg-modelines#2]
When executing package-install-file I get the following error message:

```
package-untar-buffer: Package does not untar cleanly into directory ocodo-svg-modelines-0.1.0/
```

I am on OSX using GNU Emacs 25.0.50.1.

**Comment by jasonm23** [comment]
Please detail the steps you took to create the tar.  

You may have some luck removing the `.git` folder after the git clone, and before tarring.

**Comment by jasonm23** [comment]
if you post the output of tar when you create it, that may help.

**Comment by maacl** [comment]
Steps to create tar:

```
git clone https://github.com/ocodo/ocodo-svg-modelines ~/ocodo-svg-modelines-0.1.0
rm -rf ocodo-svg-modelines-0.1.0/.git
tar cvf ocodo-svg-modelines-0.1.0.tar ~/ocodo-svg-modelines-0.1.0
```

Output from tar command after removing .git:

➜  ~  tar cvf ocodo-svg-modelines-0.1.0.tar ~/ocodo-svg-modelines-0.1.0
tar: Removing leading '/' from member names
a Users/mac/ocodo-svg-modelines-0.1.0
a Users/mac/ocodo-svg-modelines-0.1.0/images
a Users/mac/ocodo-svg-modelines-0.1.0/LICENSE
a Users/mac/ocodo-svg-modelines-0.1.0/ocodo-kawaii-light-smt.el
a Users/mac/ocodo-svg-modelines-0.1.0/ocodo-mesh-aqua-smt.el
a Users/mac/ocodo-svg-modelines-0.1.0/ocodo-mesh-grass-smt.el
a Users/mac/ocodo-svg-modelines-0.1.0/ocodo-minimal-dark-smt.el
a Users/mac/ocodo-svg-modelines-0.1.0/ocodo-minimal-light-smt.el
a Users/mac/ocodo-svg-modelines-0.1.0/ocodo-smt-overrides.el
a Users/mac/ocodo-svg-modelines-0.1.0/ocodo-steps-aqua-smt.el
a Users/mac/ocodo-svg-modelines-0.1.0/ocodo-steps-grass-smt.el
a Users/mac/ocodo-svg-modelines-0.1.0/ocodo-svg-modelines-pkg.el
a Users/mac/ocodo-svg-modelines-0.1.0/ocodo-svg-modelines.el
a Users/mac/ocodo-svg-modelines-0.1.0/README.md
a Users/mac/ocodo-svg-modelines-0.1.0/screenshots
a Users/mac/ocodo-svg-modelines-0.1.0/screenshots/ocodo-kawaii-light-smt.png
a Users/mac/ocodo-svg-modelines-0.1.0/screenshots/ocodo-mesh-aqua-smt.png
a Users/mac/ocodo-svg-modelines-0.1.0/screenshots/ocodo-mesh-grass-smt.png
a Users/mac/ocodo-svg-modelines-0.1.0/screenshots/ocodo-minimal-dark-smt.png
a Users/mac/ocodo-svg-modelines-0.1.0/screenshots/ocodo-minimal-light-smt.png
a Users/mac/ocodo-svg-modelines-0.1.0/screenshots/ocodo-steps-aqua-smt.png
a Users/mac/ocodo-svg-modelines-0.1.0/screenshots/ocodo-steps-grass-smt.png
a Users/mac/ocodo-svg-modelines-0.1.0/images/mesh-aqua.svg
a Users/mac/ocodo-svg-modelines-0.1.0/images/mesh-grass.svg
a Users/mac/ocodo-svg-modelines-0.1.0/images/rainbow-stache-banana.png
a Users/mac/ocodo-svg-modelines-0.1.0/images/steps-aqua.svg
a Users/mac/ocodo-svg-modelines-0.1.0/images/steps-grass.svg

```
package-install-file
```

still fails with:

```
package-untar-buffer: Package does not untar cleanly into directory ocodo-svg-modelines-0.1.0/
```

**Comment by jasonm23** [comment]
Looks like I need to re-do the instructions.

```
git clone https://github.com/ocodo/ocodo-svg-modelines ~/ocodo-svg-modelines-0.1.0
cd ~
tar cvf ocodo-svg-modelines-0.1.0.tar ocodo-svg-modelines-0.1.0
```

Remove the existing tar and just do:

```
cd ~
tar cvf ocodo-svg-modelines-0.1.0.tar ocodo-svg-modelines-0.1.0
```

You can then install it with `M-x package-install-file`

Sorry for the erroneous guidelines.

**Comment by jasonm23** [comment]
Updated README and Commentary

**Comment by maacl** [comment]
One step closer but now package-install-file fails with:

Leaving directory `/Users/mac/.emacs.d/elpa/ocodo-svg-modelines-0.1.0'

Compiling file /Users/mac/.emacs.d/elpa/ocodo-svg-modelines-0.1.0/ocodo-kawaii-light-smt.el at Sun May 10 18:09:52 2015
Entering directory`/Users/mac/.emacs.d/elpa/ocodo-svg-modelines-0.1.0/'
ocodo-kawaii-light-smt.el:10:1:Error: Cannot open load file: No such file or directory, svg-mode-line-themes

Compiling file /Users/mac/.emacs.d/elpa/ocodo-svg-modelines-0.1.0/ocodo-mesh-aqua-smt.el at Sun May 10 18:09:52 2015
ocodo-mesh-aqua-smt.el:10:1:Error: Cannot open load file: No such file or directory, svg-mode-line-themes

Compiling file /Users/mac/.emacs.d/elpa/ocodo-svg-modelines-0.1.0/ocodo-mesh-grass-smt.el at Sun May 10 18:09:52 2015
ocodo-mesh-grass-smt.el:10:1:Error: Cannot open load file: No such file or directory, svg-mode-line-themes

Compiling file /Users/mac/.emacs.d/elpa/ocodo-svg-modelines-0.1.0/ocodo-minimal-dark-smt.el at Sun May 10 18:09:52 2015
ocodo-minimal-dark-smt.el:10:1:Error: Cannot open load file: No such file or directory, svg-mode-line-themes

Compiling file /Users/mac/.emacs.d/elpa/ocodo-svg-modelines-0.1.0/ocodo-minimal-light-smt.el at Sun May 10 18:09:52 2015
ocodo-minimal-light-smt.el:10:1:Error: Cannot open load file: No such file or directory, svg-mode-line-themes

Compiling file /Users/mac/.emacs.d/elpa/ocodo-svg-modelines-0.1.0/ocodo-smt-overrides.el at Sun May 10 18:09:52 2015
ocodo-smt-overrides.el:4:1:Error: Cannot open load file: No such file or directory, svg-mode-line-themes

Compiling file /Users/mac/.emacs.d/elpa/ocodo-svg-modelines-0.1.0/ocodo-steps-aqua-smt.el at Sun May 10 18:09:52 2015
ocodo-steps-aqua-smt.el:10:1:Error: Cannot open load file: No such file or directory, svg-mode-line-themes

Compiling file /Users/mac/.emacs.d/elpa/ocodo-svg-modelines-0.1.0/ocodo-steps-grass-smt.el at Sun May 10 18:09:52 2015
ocodo-steps-grass-smt.el:10:1:Error: Cannot open load file: No such file or directory, svg-mode-line-themes

Compiling file /Users/mac/.emacs.d/elpa/ocodo-svg-modelines-0.1.0/ocodo-svg-modelines-pkg.el at Sun May 10 18:09:52 2015

Compiling file /Users/mac/.emacs.d/elpa/ocodo-svg-modelines-0.1.0/ocodo-svg-modelines.el at Sun May 10 18:09:52 2015
ocodo-svg-modelines.el:166:1:Error: Cannot open load file: No such file or directory, svg-mode-line-themes

ocodo-svg-modelines/init fails with:

eval-buffer: Cannot open load file: No such file or directory, svg-mode-line-themes

**Comment by jasonm23** [comment]
See the updated README, you'll need to install svg-mode-line-themes first.

**Comment by jasonm23** [comment]
Note that MELPA install will fix this up automatically, so I'll be getting that happening as soon as possible.

**Comment by maacl** [comment]
Ok, got there, but not getting a look that matches your screenshots, cf attached:

M-x ocodo-svg-modelines/init:

![default](https://cloud.githubusercontent.com/assets/64092/7555680/13d7a11a-f753-11e4-8f9d-a6c5a0b6a4dd.png)

M-x smt/set-theme [RET] ocodo-kawaii-light:smt

![ocodo-kawaii-light](https://cloud.githubusercontent.com/assets/64092/7555681/196e9160-f753-11e4-96c8-bf4ae41e0f57.png)

**Comment by jasonm23** [comment]
Which build / version of Emacs, and which OS?

**Comment by maacl** [comment]
OSX 10.10.3

emacs: stable 24.5 (bottled), devel 24.5-dev, HEAD
https://www.gnu.org/software/emacs/
/usr/local/Cellar/emacs/HEAD (3913 files, 116M) *
  Built from source with: --with-gnutls, --with-cocoa, --with-librsvg

**Comment by jasonm23** [comment]
Need Emacs Mac on OS X 

See README

**Comment by jasonm23** [comment]
Librsvg won't load external resources.   This is supposed to be fixed in Emacs 25.x

**Comment by maacl** [comment]
Now tried with GNU Emacs 25.0.50.1. with same result.

**Comment by jasonm23** [comment]
> This is supposed to be fixed in Emacs 25.x

Note it is not fixed in 25.0 so far.

Your only option is Emacs-Mac, follow the README please.

**Comment by jasonm23** [comment]
Note, I am working on a workaround for librsvg builds, 

My hypothesis is that images can be injected using the data uri scheme (svg as UTF8 text and PNG as base64.) (it works in browsers and Emacs mac port.)

I'll need to test this with a librsvg build of course.  I'll post results here.

**Comment by jasonm23** [comment]
It works.  I'll get the docs updated and get the release up.

I'll ping here as soon as it's available.

**Comment by jasonm23** [comment]
Development is in a branch 0.1.1-dev 

Png Images work this way, but external svg does not. I will need to work on this later today.

The Kawaii version works.  If you remove .elc's and replace the existing package installed files with those in the dev branch, you can happily enjoy the rainbow banana, right now.

**Comment by maacl** [comment]
Great, got it working.
